// lib/mock-data.ts
import { addDays, format, subDays, subMonths } from 'date-fns';

// Sample projects data
export const projectsData = [
  {
    id: 'p1',
    name: 'Abastecimento de Água em Lichinga',
    institution: 'aias',
    institutionName: 'AIAS',
    status: 'in-progress',
    progress: 75,
    startDate: subMonths(new Date(), 3).toISOString(),
    endDate: addDays(new Date(), 90).toISOString(),
    responsible: 'Carlos Oliveira',
  },
  {
    id: 'p2',
    name: 'Saneamento da Cidade de Maputo',
    institution: 'aias',
    institutionName: 'AIAS',
    status: 'delayed',
    progress: 45,
    startDate: subMonths(new Date(), 6).toISOString(),
    endDate: addDays(new Date(), 120).toISOString(),
    responsible: 'Ana Silva',
  },
  {
    id: 'p3',
    name: 'Gestão de Resíduos em Nampula',
    institution: 'aias',
    institutionName: 'AIAS',
    status: 'in-progress',
    progress: 60,
    startDate: subMonths(new Date(), 2).toISOString(),
    endDate: addDays(new Date(), 150).toISOString(),
    responsible: 'Manuel Costa',
  },
  {
    id: 'p4',
    name: 'Melhoria do Sistema de Água de Xai-Xai',
    institution: 'aias',
    institutionName: 'AIAS',
    status: 'completed',
    progress: 100,
    startDate: subMonths(new Date(), 8).toISOString(),
    endDate: subDays(new Date(), 15).toISOString(),
    responsible: 'Luísa Mendes',
  },
  {
    id: 'p5',
    name: 'Expansão da Rede de Água em Beira',
    institution: 'aias',
    institutionName: 'AIAS',
    status: 'pending',
    progress: 0,
    startDate: addDays(new Date(), 15).toISOString(),
    endDate: addDays(new Date(), 200).toISOString(),
    responsible: 'João Ferreira',
  },
  // Add more projects as needed for other institutions
  {
    id: 'p6',
    name: 'Reabilitação do Sistema de Água em Tete',
    institution: 'dnaas',
    institutionName: 'DNAAS',
    status: 'in-progress',
    progress: 30,
    startDate: subMonths(new Date(), 1).toISOString(),
    endDate: addDays(new Date(), 180).toISOString(),
    responsible: 'Maria Sousa',
  },
  {
    id: 'p7',
    name: 'Abastecimento de Água em Quelimane',
    institution: 'fipag',
    institutionName: 'FIPAG',
    status: 'in-progress',
    progress: 50,
    startDate: subMonths(new Date(), 4).toISOString(),
    endDate: addDays(new Date(), 60).toISOString(),
    responsible: 'Paulo Machava',
  },
];

// Sample documents data
export const documentsData = [
  {
    id: 'd1',
    name: 'Relatório Ambiental de Lichinga',
    institution: 'aias',
    type: 'relatório',
    uploadDate: subDays(new Date(), 5).toISOString(),
    size: '2.5 MB',
  },
  {
    id: 'd2',
    name: 'Plano de Ação Social Maputo',
    institution: 'aias',
    type: 'plano',
    uploadDate: subDays(new Date(), 8).toISOString(),
    size: '3.1 MB',
  },
  {
    id: 'd3',
    name: 'Avaliação Saneamento Nampula',
    institution: 'aias',
    type: 'avaliação',
    uploadDate: subDays(new Date(), 15).toISOString(),
    size: '1.8 MB',
  },
  {
    id: 'd4',
    name: 'Especificações Técnicas Xai-Xai',
    institution: 'aias',
    type: 'especificação',
    uploadDate: subDays(new Date(), 20).toISOString(),
    size: '4.2 MB',
  },
  {
    id: 'd5',
    name: 'Orçamento Expansão Beira',
    institution: 'aias',
    type: 'orçamento',
    uploadDate: subDays(new Date(), 3).toISOString(),
    size: '1.5 MB',
  },
  {
    id: 'd6',
    name: 'Estudo de Impacto Ambiental',
    institution: 'aias',
    type: 'estudo',
    uploadDate: subDays(new Date(), 25).toISOString(),
    size: '5.3 MB',
  },
  // Add more documents for other institutions
  {
    id: 'd7',
    name: 'Relatório Técnico Tete',
    institution: 'dnaas',
    type: 'relatório',
    uploadDate: subDays(new Date(), 12).toISOString(),
    size: '3.7 MB',
  },
  {
    id: 'd8',
    name: 'Plano de Implementação Quelimane',
    institution: 'fipag',
    type: 'plano',
    uploadDate: subDays(new Date(), 7).toISOString(),
    size: '2.9 MB',
  },
];

// Chart data
export const chartData = {
  projectProgress: [
    { name: 'Abastecimento de Água em Lichinga (AIAS)', progress: 75 },
    { name: 'Saneamento da Cidade de Maputo (AIAS)', progress: 45 },
    { name: 'Gestão de Resíduos em Nampula (AIAS)', progress: 60 },
    { name: 'Melhoria do Sistema de Água de Xai-Xai (AIAS)', progress: 100 },
    { name: 'Expansão da Rede de Água em Beira (AIAS)', progress: 0 },
    { name: 'Reabilitação do Sistema de Água em Tete (DNAAS)', progress: 30 },
    { name: 'Abastecimento de Água em Quelimane (FIPAG)', progress: 50 },
  ],
  projectStatus: [
    { name: 'Em Andamento', count: 4 },
    { name: 'Concluído', count: 1 },
    { name: 'Atrasado', count: 1 },
    { name: 'Pendente', count: 1 },
  ],
  monthlyProgress: [
    {
      month: 'Jan',
      Lichinga: 10,
      Maputo: 15,
      Nampula: 5,
    },
    {
      month: 'Fev',
      Lichinga: 25,
      Maputo: 20,
      Nampula: 15,
    },
    {
      month: 'Mar',
      Lichinga: 40,
      Maputo: 25,
      Nampula: 30,
    },
    {
      month: 'Abr',
      Lichinga: 55,
      Maputo: 30,
      Nampula: 40,
    },
    {
      month: 'Mai',
      Lichinga: 75,
      Maputo: 45,
      Nampula: 60,
    },
  ],
};
